[package]
name = "sqlx-ledger-cel-parser"
description = "A parser for the Common Expression Language (CEL)"
repository = "https://github.com/GaloyMoney/sqlx-ledger"
version = "0.5.13-dev"
authors = ["Justin Carter <justin@galoy.io>"]
edition = "2021"
license = "MIT"
categories = ["parsing", "cel"]

[features]

fail-on-warnings = []

[dependencies]
lalrpop-util = { git = "https://github.com/lalrpop/lalrpop.git", ref = "f7dd39d8c736c969f90c431a2eebb07383fe3a30", features = ["lexer"] }
regex = "1.4"

[build-dependencies]
lalrpop = { git = "https://github.com/lalrpop/lalrpop.git", ref = "f7dd39d8c736c969f90c431a2eebb07383fe3a30", features = ["lexer"] }
