[package]
name = "cel-interpreter"
version = "0.1.0"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]

chrono = "0.4.22"
cel-parser = { path="../cel-parser" }
serde = "1.0.147"
serde_json = "1.0.87"
thiserror = "1.0.37"
uuid = { version = "1.2.1", features = ["serde", "v4"] }
