#@ load("@ytt:data", "data")

#@ load("vendor/pipeline-fragments.lib.yml",
#@   "build_edge_image",
#@   "public_docker_registry",
#@   "rust_check_code",
#@   "rust_integration_test",
#@   "repo_resource",
#@   "edge_image_resource",
#@   "version_resource",
#@   "gh_release_resource",
#@   "pipeline_tasks_resource",
#@   "release_task_image_config",
#@   "rust_task_image_config",
#@   "charts_repo_resource",
#@   "charts_repo_bot_branch",
#@   "slack_resource_type",
#@   "slack_resource",
#@   "slack_failure_notification"
#@ )

groups:
- name: sqlx-ledger
  jobs:
    - check-code
    - test-integration

jobs:
- #@ rust_check_code()
- name: test-integration
  serial: true
  plan:
  - in_parallel:
    - { get: repo, trigger: true }
    - { get: pipeline-tasks }
  - task: test-integration
    timeout: 12m
    tags: ["galoy-staging"]
    config:
      platform: linux
      image_resource: #@ rust_task_image_config()
      inputs:
      - name: pipeline-tasks
      - name: repo
        path: #@ data.values.gh_repository + "-integration"
      caches:
      - path: cargo-home
      - path: cargo-target-dir
      params:
        REPO_PATH: #@ data.values.gh_repository + "-integration"
        DOCKER_HOST_IP: ((staging-ssh.docker_host_ip))
        GOOGLE_CREDENTIALS: ((staging-gcp-creds.creds_json))
        SSH_PRIVATE_KEY: ((staging-ssh.ssh_private_key))
        SSH_PUB_KEY: ((staging-ssh.ssh_public_key))
      run:
        path: pipeline-tasks/ci/tasks/test-integration.sh
  on_failure: #@ slack_failure_notification()
  
resources:
- #@ repo_resource()
- #@ pipeline_tasks_resource()
- #@ slack_resource()

resource_types:
- #@ slack_resource_type()
